trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'kishjet docker'
    repository: 'kishjet/formulapi'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
