services:
  formulapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: formulapi-${NODE_ENV}
    environment:
      DATABASE_URL: ${DATABASE_URL}
      HOST: ${HOST}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}" # Cannot access locally if port is not exposed
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "256M"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://${HOST}:${PORT}/health"]
      start_period: 1m
      interval: 1m
      timeout: 10s
      retries: 3