name: Node.js Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install pnpm
      run: npm install -g pnpm
        
    - name: Install Dependencies
      run: pnpm install

    - name: Generate Prisma Client
      run: npx prisma generate
      
    - name: Build Project
      run: pnpm build

    - name: Start API Server
      run: pnpm start &

    - name: Wait for API Server to start
      run: sleep 5

    - name: Run Tests
      run: pnpm test
