name: Build and Test

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
            PORT: ${{ secrets.PORT }}
            JWT_SECRET: ${{ secrets.JWT_SECRET }}
            HOST: ${{ secrets.HOST }}
        strategy:
            matrix:
                node-version: [20.x]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Install pnpm
              uses: pnpm/action-setup@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
            - name: Install Dependencies
              run: pnpm install --frozen-lockfile
            - name: Audit Dependencies
              run: pnpm audit
            - name: Lint code
              run: pnpm lint
            - name: Build Project
              run: pnpm build
            - name: Run Tests
              run: pnpm test -- --coverage
            - name: SonarCloud Scan
              uses: SonarSource/sonarcloud-github-action@master
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}