name: Build and Test

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
            DIRECT_URL: ${{ secrets.DIRECT_URL }}
            APP_PORT: ${{ secrets.APP_PORT }}
            APP_URL: ${{ secrets.APP_URL }}
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Install pnpm
              uses: pnpm/action-setup@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
            - name: Install Dependencies
              run: pnpm install --frozen-lockfile
            - name: Lint code
              run: pnpm lint
            - name: Build Project
              run: pnpm build
            - name: Run Tests
              run: pnpm test -- --coverage
            - name: Audit Dependencies
              run: pnpm audit
            - name: SonarCloud Scan
              uses: SonarSource/sonarcloud-github-action@master
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
