name: Deploy to Development environment

on:
    workflow_run:
        workflows:
            - "Build and Test Docker Container"
        types:
            - completed

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: 
            name: development
            url: "https://formulapi-dev.kjet.ipv64.net"
        steps:
            - name: Deploy to Coolify
              run: |
                  curl --request GET '${{ secrets.COOLIFY_WEBHOOK }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'
