name: Build and Push Docker Image

on:
    workflow_run:
        workflows: ["Build and Test"]
        types:
            - completed

jobs:
    build:
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        env:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
            APP_PORT: ${{ secrets.APP_PORT }}
        steps:
            - uses: actions/checkout@v4
            - name: Login to Docker
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build the Docker image
              run: docker build . --file Dockerfile --tag kishjet/formulapi:${{ github.sha }}
            - name: Push the Docker image
              run: docker push kishjet/formulapi:${{ github.sha }}
            - name: Deploy to Development environment
              run: |
                  curl --request GET '${{ secrets.COOLIFY_WEBHOOK }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'
