name: Build and Test Docker Container

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    docker:
        runs-on: ubuntu-latest
        env:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
            PORT: ${{ secrets.PORT }}
            JWT_SECRET: ${{ secrets.JWT_SECRET }}
            HOST: ${{ secrets.HOST }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Build and run Docker container
              run: |
                  docker-compose up --build -d
            - name: Run Tests
              run: |
                  docker-compose exec formulapi pnpm test
