name: Node.js Tests

on:
  workflow_run:
    workflows: ["Node.js Build"]
    types:
      - completed
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci
    
    - name: Setup Prisma
      run: npx prisma generate

    - name: Start API Server
      run: npm run start &

    - name: Wait for API to Start
      run: sleep 5

    - name: Run Tests
      run: npm test
